site_name: Strongbox
repo_name: 'strongbox/strongbox'
repo_url: 'https://github.com/strongbox/strongbox'
edit_uri: 'https://github.com/strongbox/strongbox-docs/edit/master/docs'
theme:
  name: material
  logo: ''
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  language: en
  feature:
    tabs: true

extra_css:
  - 'assets/stylesheets/style.css'

extra_javascript:
  - 'assets/javascripts/medium-zoom.min.js'
  - 'assets/javascripts/main.js'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Introduction: index.md
  - Release notes: release-notes.md
  - Contributing: contributing.md
  - License: license.md
  - User guide:
    - Getting started: user-guide/getting-started.md
    - Application properties: user-guide/application-properties.md
    - Upgrading: user-guide/upgrading.md
    - User Interface:
      - Browsing: user-guide/ui/browsing.md
      - System Information: user-guide/ui/system-information.md
  - Join chat:
    - Join chat: chat-redirect.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
